import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import Subscribe from "@/components/Subscribe";

export const metadata = {
  title: "Testimonials",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar />
      {children}
      <Subscribe />
      <Footer />
      </body>
    </html>
  );
}
